aroningruber/scryfall_api

.gitignore, lib/src/models/card_face.dart, lib/src/models/card_face.g.dart, lib/src/models/mtg_card.dart, lib/src/models/mtg_card.g.dart, lib/src/scryfall_api_client.dart, test/scryfall_api_client_test.dart
=> Implement GET /cards/search; Cleanup tests

lib/src/scryfall_api_client.dart, test/mock_data/get_card_by_name.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/named

lib/src/models/catalog.dart, lib/src/models/catalog.g.dart, lib/src/models/models.dart, lib/src/models/paginable_list.dart, lib/src/scryfall_api_client.dart, test/mock_data/autocomplete_card_name.json, test/models/catalog_test.dart, test/scryfall_api_client_test.dart
=> Implement GET /cards/autocomplete

lib/src/scryfall_api_client.dart, test/mock_data/get_random_card.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/random

lib/src/models/language.dart, lib/src/models/language.g.dart, lib/src/models/models.dart, lib/src/models/mtg_card.dart, lib/src/models/mtg_card.g.dart, lib/src/scryfall_api_client.dart, test/mock_data/get_card_by_set_code_and_collector_number.json, test/models/language_test.dart, test/models/mtg_card_test.dart, test/scryfall_api_client_test.dart
=> Implement GET /cards/:code/:number(/:lang)

lib/src/scryfall_api_client.dart, test/mock_data/get_card_by_multiverse_id.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/multiverse/:id

lib/src/scryfall_api_client.dart, test/mock_data/get_card_by_mtgo_id.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/mtgo/:id

lib/src/scryfall_api_client.dart, test/mock_data/get_card_by_arena_id.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/arena/:id

lib/src/scryfall_api_client.dart, test/mock_data/get_card_by_tcgplayer_id.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/tcgplayer/:id

lib/src/scryfall_api_client.dart, test/mock_data/get_card_by_cardmarket_id.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/cardmarket/:id

lib/src/scryfall_api_client.dart, test/mock_data/get_card_by_id.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/:id

lib/src/scryfall_api_client.dart, test/mock_data/get_rulings_by_multiverse_id.json, test/scryfall_api_client_test.dart
=> [#20] Add method to get rulings by multiverse id

lib/src/scryfall_api_client.dart, test/mock_data/get_rulings_by_arena_id.json, test/scryfall_api_client_test.dart
=> [#22] Add method to get rulings by arena id

lib/src/scryfall_api_client.dart, test/mock_data/get_rulings_by_set_code_and_collector_number.json, test/scryfall_api_client_test.dart
=> [#23] Add method to get rulings by set code and collector number

lib/src/scryfall_api_client.dart, test/mock_data/get_rulings_by_id.json, test/scryfall_api_client_test.dart
=> Implement GET /cards/:id/rulings

lib/src/models/card_symbol.dart, lib/src/models/card_symbol.g.dart, lib/src/scryfall_api_client.dart, test/mock_data/get_all_card_symbols.json, test/scryfall_api_client_test.dart
=> Implement GET /symbology

lib/src/models/mana_cost.dart, lib/src/models/mana_cost.g.dart, lib/src/models/models.dart, lib/src/scryfall_api_client.dart, test/mock_data/parse_mana.json, test/models/mana_cost_test.dart, test/scryfall_api_client_test.dart
=> Implement GET /symbology/parse-mana

README.md, lib/src/models/language.dart, lib/src/scryfall_api_client.dart, test/mock_data/get_catalog.json, test/models/language_test.dart, test/scryfall_api_client_test.dart
=> Implement GET /catalog/**

lib/src/scryfall_api_client.dart, test/mock_data/get_bulk_data_by_type.json, test/scryfall_api_client_test.dart
=> Implement GET /bulk-data/:type

lib/src/models/bulk_data.dart, lib/src/models/bulk_data.g.dart, test/mock_data/get_bulk_data.json, test/mock_data/get_bulk_data_by_id.json, test/mock_data/get_bulk_data_by_type.json, test/models/bulk_data_test.dart
Changed 'compressed_size' to 'size' and made nullable.
=> Bulk data fix
